### ISSUE TITLE
创建属性时，填写的属性默认值，在保存之后，发现获取到的默认值不是填写的默认值

### ISSUE THREAD

**Issue by jeawy** [jeawy/wkflow#1]

**Comment by jeawy** [comment]
![QQ截图20190716231113](https://user-images.githubusercontent.com/20496897/61306355-09993980-a81f-11e9-9dda-27995451e519.png)
![QQ图片20190716231040](https://user-images.githubusercontent.com/20496897/61306358-09993980-a81f-11e9-8a63-9213c65d1d59.png)

**Comment by jeawy** [comment]
@ @ @ @ @freeNeasy-lc 卢晨，你看一下这个bug

**Comment by freeNeasy-lc** [comment]
bug已解决
